# Generated by Django 4.2.7 on 2023-11-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyQuiz',
        ),
    ]
