# Generated by Django 4.2.7 on 2023-11-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_rename_impromptuquiz_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(default='')),
                ('topic', models.CharField(default='', max_length=100)),
                ('question', models.TextField()),
            ],
        ),
    ]
