# Generated by Django 4.2.7 on 2023-11-09 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_surveyquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquiz',
            name='id',
        ),
        migrations.AddField(
            model_name='surveyquiz',
            name='surveyquiz_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
