# Generated by Django 4.2.7 on 2023-11-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_rename_quiz_impromptuquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='impromptuquiz',
            name='section',
            field=models.CharField(default='돌발주제', max_length=100),
        ),
        migrations.AddField(
            model_name='surveyquiz',
            name='section',
            field=models.CharField(default='선택주제', max_length=100),
        ),
    ]
