# Generated by Django 4.2.7 on 2023-11-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_impromptuquiz_section_surveyquiz_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impromptuquiz',
            name='section',
            field=models.CharField(default='돌발질문', max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyquiz',
            name='section',
            field=models.CharField(default='선택질문', max_length=100),
        ),
    ]
