# Generated by Django 4.2.7 on 2023-11-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_alter_impromptuquiz_section_alter_surveyquiz_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impromptuquiz',
            name='section',
            field=models.CharField(default='돌발주제', max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyquiz',
            name='section',
            field=models.CharField(default='선택주제', max_length=100),
        ),
    ]
